/**
 * Exports the PayToChatEscrow ABI from the compiled artifacts to a typed
 * TS const in the Next.js app, so viem / wagmi can infer types when
 * the frontend calls deposit/claim/refund/etc.
 *
 * Run after every contract change:
 *   pnpm build && npx hardhat run scripts/export-abi.ts
 */

import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";

const ARTIFACT = resolve(
  __dirname,
  "..",
  "artifacts",
  "src",
  "PayToChatEscrow.sol",
  "PayToChatEscrow.json",
);
const OUT = resolve(
  __dirname,
  "..",
  "..",
  "src",
  "lib",
  "payments",
  "escrow-abi.ts",
);

async function main() {
  const json = JSON.parse(readFileSync(ARTIFACT, "utf8"));
  const abi = json.abi;
  const body = `// AUTO-GENERATED by contracts/scripts/export-abi.ts.
// Edit the source contract and re-run \`npx hardhat run scripts/export-abi.ts\`.
//
// Compiled from contracts/src/PayToChatEscrow.sol on ${new Date().toISOString()}.

export const escrowAbi = ${JSON.stringify(abi, null, 2)} as const;
export type EscrowAbi = typeof escrowAbi;
`;
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, body);
  console.log(`wrote ${OUT}  (${abi.length} ABI entries)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
