import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Pay to Chat",
    short_name: "PayToChat",
    description:
      "Make people pay to land in your inbox. Stablecoin tips on Solana or Ethereum.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#0b0b10",
    theme_color: "#7c5cff",
    categories: ["social", "finance", "productivity"],
    icons: [
      // Browser tab / SERP favicon — generated by `app/icon.tsx`.
      {
        src: "/icon",
        sizes: "32x32",
        type: "image/png",
      },
      // iOS home-screen icon — generated by `app/apple-icon.tsx`.
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
      },
      // Android home-screen — Chrome wants a 192 and a 512. We serve a
      // single 512 (`app/icon-512/route.tsx`) and let the OS downscale.
      {
        src: "/icon-512",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      // Maskable variant for Android adaptive icons.
      {
        src: "/icon-512",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
